#!/usr/bin/env bash

exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -euxo pipefail

if [[ "$CODESPACES" = "true" ]]; then
  sudo apt-get install -y \
    fzf \
    rcm \
    zsh

  RCRC=$(pwd)/rcrc rcup -f -v -d . -t codespaces
  chsh -s /bin/zsh root
elif [[ "$(uname)" = "Darwin" ]]; then
  echo "error: still using dotfiles-local for now"
  exit 1
else
  echo "error: Unknown system"
  exit 1
fi
