#!/usr/bin/env bash

exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -euxo pipefail

if [[ "${CODESPACES:-false}" = "true" ]]; then
  sudo apt-get install -y \
    fzf \
    rcm \
    silversearcher-ag \
    universal-ctags \
    zsh

  RCRC=$(pwd)/rcrc rcup -f -v -d . -t codespaces

  sudo chsh -s /bin/zsh $(whoami)
  vim +PlugInstall +qa
elif [[ "$(uname)" = "Darwin" ]]; then
  script/bootstrap-macos
else
  echo "error: Unknown system"
  exit 1
fi
